version: '2.2'
services:
  project-manager-app:
   container_name: project-manager-app
   image: alagappanannamalai/project-manager-app:latest
   ports:
     - "8000:8000"
   depends_on:
     mysql:
       condition: service_healthy
   restart: always
    
  mysql:
      container_name: mysql-docker
      image: mysql/mysql-server:latest
      environment:
        MYSQL_DATABASE: projectmanager
        MYSQL_ROOT_PASSWORD: pass@word1
        MYSQL_ROOT_HOST: '%'
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 20s
        retries: 20
      restart: always
      
